export const actions = {
  UPDATE_INSTRUMENTS: 'UPDATE_INSTRUMENTS',
  FIND_INSTRUMENT: 'FIND_INSTRUMENT',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED'
}
